version: "3"
services:
  balancer:
    build:
      context: .
      dockerfile: Dockerfile-balancer
    ports:
      - "65432:65432"
    depends_on:
      - redis
      - server_1
      - server_2
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  redis:
    image: redis

  server_1:
    build:
      context: .
      dockerfile: Dockerfile-server

  server_2:
    build:
      context: .
      dockerfile: Dockerfile-server
    depends_on:
      - mongo